### ISSUE TITLE
error trying to run client

### ISSUE THREAD

**Issue by vv111y** [jacenkow/gpu-sentry#8]
Here's the traceback:
```
Unhandled error in Deferred:

Traceback (most recent call last):
  File "cli.py", line 42, in cli
    run_client()
  File "/home/will/DevWorkspace/gpu-sentry/gpu_sentry/client.py", line 90, in run_client
    l.start(config.CLIENT_TIMEOUT)
  File "/home/will/anaconda3/lib/python3.6/site-packages/twisted/internet/task.py", line 194, in start
    self()
  File "/home/will/anaconda3/lib/python3.6/site-packages/twisted/internet/task.py", line 239, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/home/will/anaconda3/lib/python3.6/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "/home/will/DevWorkspace/gpu-sentry/gpu_sentry/client.py", line 81, in send_statistics
    json={"codename": config.PERMIT_CLIENTS[host]['codename'],
builtins.KeyError: 'gpgpu'
```

Also, if I try to run outside of /gpu-sentry/gpu_sentry I get
```
python: can't open file 'cli.py': [Errno 2] No such file or directory
```

**Comment by kshiteesh** [comment]
I get the same traceback error. Any solution yet?

**Comment by rknidzam** [comment]
Anyone fixes this error?

**Comment by henry8904** [comment]
same as I
